app = "deviante-api"
primary_region = "iad"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["api"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = 15000
    timeout = 10000
    grace_period = "60s"
    path = "/ping"

[processes]
  api = "java -jar /app/app.jar"
