app = "deviante-api"
primary_region = "sa-east-1"

[build]
  image = "eclipse-temurin:21-jdk"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["api"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = 15000
    timeout = 5000
    grace_period = "10s"
    path = "/ping"

[processes]
  api = "./gradlew run"
